image = "registry.gitlab.com/kentang-goreng/talent_talent_dashboard"
imagetag = "latest"
repository = ""
registry = "gitlab_viavalen"
domain = "talent.co"
deployimg = "registry.gitlab.com/viavallen/kentang-goreng/talent_talent_dashboard:latest"
