image: quay.io/rizoa/pegasus-builder
push_github:
  only:
    refs:
    - main
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[deploy]/
  script:
  - git config --global user.email "hanirizo@gmail.com"
  - git config --global user.name "Riza Masykur"
  - git checkout main
  - repo=`cat .repo`; git remote add github $repo
  - git push -u --set-upstream github main
  services:
  - quay.io/rizoa/pegasus-builder
  stage: build
stages:
- build
variables:
  AUTHOR: Riza Masykur
