version: '3.3'
services:
    app:
        container_name: konverzi_2022_dash
        build:
            context: ./
            dockerfile: Dockerfile-dev
        volumes:
            - ./:/home
        command: yarn dev
        environment:
            - STAGE=dev
        labels:
            - traefik.enable=true
            - traefik.http.services.konverzi_2022_dash.loadbalancer.server.port=3000
            - traefik.http.routers.konverzi_2022_dash.rule=Host(`konverzi.local.net`)
            - traefik.http.routers.konverzi_2022_dash.entrypoints=web
networks:
    default:
        external:
            name: ikamai_apps
