version: '3.3'
services:
    app:
        container_name: ikamai_rootenv_dash
        build:
            context: ./
            dockerfile: Dockerfile-dev
        volumes:
            - ./:/home
        command: yarn dev
        environment:
            - STAGE=dev
        labels:
            - traefik.enable=true
            - traefik.http.services.ikamai_rootenv_dash.loadbalancer.server.port=3000
            - traefik.http.routers.ikamai_rootenv_dash.rule=Host(`aimi.app.local.net`)
            - traefik.http.routers.ikamai_rootenv_dash.entrypoints=web
networks:
    default:
        external:
            name: ikamai_apps
